[TAIPY]

[DATA_NODE.initial_dataset]
storage_type = "csv"
path = "src/data/data.csv"
has_header = "True:bool"

[DATA_NODE.date]
default_data = "None"

[DATA_NODE.preprocessed_dataset_scaled]

[DATA_NODE.preprocess_dataset_unscaled]

[DATA_NODE.predictions_AC]
storage_type = "csv"

[DATA_NODE.predictions_KM]
storage_type = "csv"

[TASK.preprocess_dataset]
function = "algos.preprocess_dataset:function"
inputs = [ "initial_dataset:SECTION", "date:SECTION",]
outputs = [ "preprocessed_dataset_scaled:SECTION", "preprocess_dataset_unscaled:SECTION",]
skippable = "False:bool"

[TASK.train_model_AC]
function = "algos.train_model_AC:function"
inputs = [ "preprocessed_dataset_scaled:SECTION",]
outputs = [ "predictions_AC:SECTION",]
skippable = "False:bool"

[TASK.train_model_KM]
function = "algos.train_model_KM:function"
inputs = [ "preprocessed_dataset_scaled:SECTION",]
outputs = [ "predictions_KM:SECTION",]
skippable = "False:bool"

[SCENARIO.customer_segmentation]
tasks = [ "preprocess_dataset:SECTION", "train_model_AC:SECTION", "train_model_KM:SECTION",]
additional_data_nodes = []

[SCENARIO.customer_segmentation.comparators]

[SCENARIO.customer_segmentation.sequences]
