[TAIPY]

[DATA_NODE.initial_dataset]
storage_type = "csv"
path = "src/data/data.csv"
has_header = "True:bool"

[DATA_NODE.date]
default_data = "None"

[DATA_NODE.preprocessed_dataset]

[DATA_NODE.trained_model]

[TASK.preprocess_dataset]
function = "algos.preprocess_dataset:function"
inputs = [ "initial_dataset:SECTION", "date:SECTION",]
outputs = [ "preprocessed_dataset:SECTION",]
skippable = "False:bool"

[TASK.train_model]
function = "algos.train_model:function"
inputs = [ "preprocessed_dataset:SECTION",]
outputs = [ "trained_model:SECTION",]
skippable = "False:bool"

[SCENARIO.customer_segmentation]
tasks = [ "preprocess_dataset:SECTION", "train_model:SECTION",]
additional_data_nodes = []

[SCENARIO.customer_segmentation.comparators]

[SCENARIO.customer_segmentation.sequences]
